### ISSUE TITLE
Fichier *Standard Credentials Files non trouvé - version 2.0.0-beta2 Windows-10-10.0.17134-SP0

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-2-office#29]
Pour reproduire : 

1. Ouvrir l'application
2. Aller dans le menu "Paramétres"
3. Changer les paramètres d'authentification
4. Importer le fichier json
5. L'explorateur Windows s'ouvre sur votre dossier "Téléchargement" mais aucun fichier ne s'affiche
6. Dans la liste des formats de fichiers recherchés sélectionner "JSON Files" au lieu de "Standard Credentials Files" 
7. Le fichier s'affiche

**Comment by Guts** [comment]
Presque certain que ton fichier a été incrémenté parce que tu en a stéléchargé d'autre, genre `client_secrets (1).json`.

=> Confirmé par le  fichier log (ligne37) ;).

On peut en discuter mais d'après moi, un client final ne devrait pas rencontrer ce cas de figure puisqu'il n'a qu'un seul fichier client_secrets.json (qui est déplacé une fois importé - comportement similaire dans le plugin pour QGIS). Et si ça venait à se produire, il peut changer le filtre. Et ne plus y penser.

Dans tous les cas, ce n'est pas un bug.

**Comment by vblanlot** [comment]
Je confirme qu'il faille nécessairement changer le filtre pour voir le fichier JSON

Captures d'écrans : 
![client_secret_1](https://user-images.githubusercontent.com/14051239/45205596-e73fa280-b282-11e8-9ecb-d9d12261dc0b.PNG)

![client_secret_2](https://user-images.githubusercontent.com/14051239/45205609-eeff4700-b282-11e8-9315-bba104583d65.PNG)

**Comment by Guts** [comment]
ok. donc comportement attendu. Je ferme du coup :)
