### ISSUE TITLE
La fenêtre windows de sélection du client secret persiste - version 2.0.0-beta2 Windows-10-10.0.17134-SP0

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-2-office#30]
Pour reproduire : 

1. Ouvrir l'application
2. Aller dans le menu "Paramétres"
3. Changer les paramètres d'authentification
4. Importer le fichier client_secret.json
5. L'explorateur Windows s'ouvre sur votre dossier "Téléchargement" mais aucun fichier ne s'affiche
6. Dans la liste des formats de fichiers recherchés sélectionner "JSON Files" au lieu de "Standard Credentials Files"
7. Le fichier s'affiche
8. Selectionner le fichier
9. Valider
10. La fenêtre Windows se ferme puis se ré-ouvre
11. Refermer la fenêtre, enfin vous pouvez sauvegarder vos nouveaux paramètres d'authentification

**Comment by vblanlot** [comment]
Log : 
[log_IsogeoToOffice.log](https://github.com/isogeo/isogeo-2-office/files/2357461/log_IsogeoToOffice.log)

**Comment by vblanlot** [comment]
Voici

1. Ouvrir l'application
2. Aller dans le menu "Paramétres"
3. Changer les paramètres d'authentification
4. Importer le fichier client_secret.json
5. L'explorateur Windows s'ouvre sur votre dossier "Téléchargement" 
6. Selectionner le fichier client_secret.json
7. Valider
8. Sauvegarder les paramètres

**Comment by Guts** [comment]
Duplicate of #31
