### ISSUE TITLE
Dans la fenêtre "Paramètres d'authentification à l'API" les boutons Enregistrer et Annuler sont affichés en anglais - version 2.0.0-beta2 Windows-10-10.0.17134-SP0

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-2-office#32]
Voir capture 
![english](https://user-images.githubusercontent.com/14051239/45163661-2b826280-b1f1-11e8-87fc-a7113416113c.PNG)

**Comment by vblanlot** [comment]
Le texte affiché dans "Pas encore de compte" est également in english

**Comment by Guts** [comment]
Le problème vient du fait que ces boutons sont standards dans Qt. Les textes sont donc censés être automatiquement traduits mais apparemment il y a des soucis. Je vais forcer la traduction au lancement.

> Le texte affiché dans "Pas encore de compte" est également in english
Voir #37
