### ISSUE TITLE
Le bouton de signalement n'a pas d'info-bulle - version 2.0.0-beta1 Windows Windows-10-10.0.17134-SP0

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-2-office#33]
Dans l'onglet "Paramètres" le bouton de signalement d'une anomalie n'affiche pas d'info-bulle

**Comment by Guts** [comment]
Indiquer l'infobulle à ajouter stp.

**Comment by vblanlot** [comment]
"Signaler un problème sur le bug tracker"

**Comment by Guts** [comment]
![image](https://user-images.githubusercontent.com/1596222/45207003-e6107480-b286-11e8-88f1-20d0a9e53f8d.png)
