### ISSUE TITLE
Le bouton demander un accés à l'application ne fonctionne pas - version 2.0.0-beta2 Windows-10-10.0.17134-SP0

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-2-office#34]
Dans la fenetre "Isogeo - Paramètres d'authentification à l'API" le bouton "Demander un accés" ne fonctionne pas

**Comment by Guts** [comment]
Que faire avec ce bouton ?

Dans les précédentes versions, il envoyait un mail préformaté.
Dans le plugin QGIS, il renvoie vers un formulaire pipedrive.

Qu'en penses-tu @vblanlot ?

**Comment by vblanlot** [comment]
Je suis pour le formulaire Pipedrive

**Comment by Guts** [comment]
Liens :

- en français : https://pipedrivewebforms.com/form/427397f21f1417e5b937b673dfa12c9052944
- en anglais : https://pipedrivewebforms.com/form/b5bdbdb9b34c3c61202cd8414accbbe252944

**Comment by Guts** [comment]
@vblanlot tu te charges de la trad du formulaire pipe en anglais stp ?

**Comment by vblanlot** [comment]
c'est fait : https://pipedrivewebforms.com/form/b5bdbdb9b34c3c61202cd8414accbbe252944
