### ISSUE TITLE
Dans le fichier Excel exporté les hyperliens "Editer" et "Consulter" ne fonctionnent pas - version 2.0.0-beta2 Windows-10-10.0.17134-SP0

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-2-office#35]
Pour reproduire

Test réalisé avec l'application isogeo2office - démonstration
Fichier exporté ici : 
[isogeo2office_.xlsx](https://github.com/isogeo/isogeo-2-office/files/2357512/isogeo2office_.xlsx)

1. Ouvrir l'application
2. Exporter vos fiches de métadonnées au format Excel
3. Ouvrir le fichier Excel
4. Aller dans l'onglet "Vecteur" "Raster" "Services" ou "Ressources"
5. Aller dans la colonne "Editer"
6. Cliquer sur le lien "Editer" **APP s'ouvre sur le tableau de bord et non sur la fiche editable**
7. Aller dans la colonne "Consulter"
8. Cliquer sur le lien "Version en ligne"
9. Excel indique que **l'url demandée n'existe pas (404)**

**Comment by Guts** [comment]
> Cliquer sur le lien "Editer" APP s'ouvre sur le tableau de bord et non sur la fiche editable

Impossible de changer ce comportement, c'est un problème lié à Excel. Je ne trouve aucun moyen de contournement.

> Excel indique que l'url demandée n'existe pas (404)

En cours de correction.
