### ISSUE TITLE
Le dossier de destination des exports n'est pas pris en compte - version 2.0.0-beta2 Windows-10-10.0.17134-SP0

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-2-office#36]
Pour reproduire

1. Ouvrir l'application
2. Dans l'onglet paramètres, changer le dossier de destination des exports
3. Exporter
4. Aller dans le dossier indiqué, il est vide
5. Aller dans le dossier par défaut ...isogeo2office\output l'export y est stocké

**Comment by Guts** [comment]
#28
