### ISSUE TITLE
Définir le texte pour les utilisateurs ne disposant pas de clés d'authentification

### ISSUE THREAD

**Issue by Guts** [isogeo/isogeo-2-office#37]
cf https://github.com/isogeo/isogeo-2-office/issues/32#issuecomment-419113404

**Texte actuel**

*en anglais*

<ul>
	<li>Completely free to access generic Open Data</li>
	<li>Completely free to work with 20 of your geographic data and services (Isogeo account required)</li>
	<li>Ask for our annual plans to work with your whole geographic data and services !</li>
</ul> 

*en français*

<ul>
	<li>Gratuit pour accéder à un ensemble générique de données ouvertes</li>
	<li>Gratuit pour accéder jusqu'à 20 données et services géographiques à documenter soi-même sur Isogeo</li>
	<li>Des abonnements pour accéder à l'ensemble des données et services de son organisme... et d'autres aussi !</li>
</ul> 

**Question**

Ce texte ne semble pas/plus très adapté, non ?

**Comment by vblanlot** [comment]
En effet c'est peut-être plus vraiment adapté. En attendant une décision, je suis pour le conserver.

**Comment by Guts** [comment]
Ok. Il est bien traduit dans la denière version. Je laisse ouvert le temps qu'on se décide ensemble.
