### ISSUE TITLE
La modification des paramètres d'authentification ferme l'application

### ISSUE THREAD

**Issue by vblanlot** [isogeo/isogeo-2-office#42]
Pour reproduire : 

1. Ouvrir l'application
2. Aller dans le menu paramètres > paramètres d'authentification
3. Changer les paramètres d'authentification
4. L'application se ferme

Log : 
[log_IsogeoToOffice.log](https://github.com/isogeo/isogeo-2-office/files/2400645/log_IsogeoToOffice.log)

**Comment by vblanlot** [comment]
Pour info, le dossier _auth est vide

**Comment by Guts** [comment]
-_- ... je vois ce que sais, je corrige
